baseURL = 'https://galerkin.github.io/'
languageCode = 'ko'
title = 'Brain dump'
theme = 'hugo-bearblog'
[pagination]
pagerSize = 5
summaryLength = 30
[params]
description = 'Jaesung'
author = 'Jaesung Eom'
[markup.goldmark.renderer]
unsafe = true
